from app.llm_client import generate_text
from app.prompts import SUMMARY_PROMPT


def summarize_text(text: str) -> str:
    """
    Generate a concise summary of the provided text.

    Args:
        text: The text that needs to be summarized.

    Returns:
        A concise summary generated by the configured LLM.

    Raises:
        TypeError: If the input is not a string.
        ValueError: If the input is empty or too short.
        RuntimeError: If the LLM API request fails.
    """

    # Validate data type
    if not isinstance(text, str):
        raise TypeError("Text must be a string.")

    # Remove unnecessary whitespace
    text = text.strip()

    # Validate empty input
    if not text:
        raise ValueError("Text cannot be empty.")

    # Validate minimum length
    if len(text) < 50:
        raise ValueError(
            "Text is too short to generate a meaningful summary."
        )

    # Build the prompt
    prompt = SUMMARY_PROMPT.format(text=text)

    # Generate summary through configured LLM provider
    summary = generate_text(prompt)

    return summary