from app.llm_client import generate_text
from app.prompts import SUMMARY_PROMPT


MIN_TEXT_LENGTH = 50


def summarize_text(text: str) -> str:
    """
    Generate a concise summary of the provided text.

    Args:
        text: The text that needs to be summarized.

    Returns:
        A concise summary generated by the configured LLM.

    Raises:
        TypeError: If the input is not a string.
        ValueError: If the input is empty or too short.
        RuntimeError: If the LLM API request fails.
    """

    if not isinstance(text, str):
        raise TypeError("Text must be a string.")

    text = text.strip()

    if not text:
        raise ValueError("Text cannot be empty.")

    if len(text) < MIN_TEXT_LENGTH:
        raise ValueError(
            "Text is too short to generate a meaningful summary."
        )

    prompt = SUMMARY_PROMPT.format(text=text)

    return generate_text(prompt)